name: @@NAME@@
version: @@VERSION@@
summary: Code editing. Redefined.
description: |
  Visual Studio Code is a new choice of tool that combines the
  simplicity of a code editor with what developers need for the core
  edit-build-debug cycle.

grade: stable
confinement: classic

parts:
  code:
    plugin: dump
    source: .
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
      # desktop-gtk2 deps below
      - libxkbcommon0
      - libgtk2.0-0
      # - unity-gtk2-module
      - libappindicator1
    prime:
      - -usr/share/dh-python
  electron-launch:
    plugin: dump
    source: .
    organize:
      electron-launch: bin/electron-launch

apps:
  @@NAME@@:
    command: bin/electron-launch ${SNAP}/usr/share/@@NAME@@/bin/@@NAME@@
    desktop: usr/share/applications/@@NAME@@.desktop